import { Product } from './types';

const today = new Date().toISOString();
const weekAgo = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString();
const monthAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Abaya Fatou',
    description: 'Abaya classique en Nida, coupe fluide et élégante. Parfaite pour le quotidien avec une touche de raffinement sénégalais.',
    price: 18000,
    category: 'Abaya classique',
    fabric: 'Nida',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Noir', hex: '#1A1A1A' },
      { name: 'Bleu nuit', hex: '#1B2A4A' },
      { name: 'Prune', hex: '#4A1942' },
    ],
    variants: [
      { size: 'S', color: 'Noir', stock: 5, alertThreshold: 2 },
      { size: 'M', color: 'Noir', stock: 8, alertThreshold: 2 },
      { size: 'L', color: 'Noir', stock: 3, alertThreshold: 2 },
      { size: 'XL', color: 'Noir', stock: 2, alertThreshold: 2 },
      { size: 'S', color: 'Bleu nuit', stock: 4, alertThreshold: 2 },
      { size: 'M', color: 'Bleu nuit', stock: 6, alertThreshold: 2 },
      { size: 'L', color: 'Bleu nuit', stock: 0, alertThreshold: 2 },
      { size: 'M', color: 'Prune', stock: 3, alertThreshold: 2 },
      { size: 'L', color: 'Prune', stock: 5, alertThreshold: 2 },
    ],
    images: ['https://placehold.co/400x500/F5F0E8/3D1A47?text=Abaya+Fatou'],
    isNew: false,
    isActive: true,
    createdAt: monthAgo,
  },
  {
    id: 'p2',
    name: 'Abaya Aïssatou Royale',
    description: 'Abaya de cérémonie en Soie de Médine avec broderies dorées subtiles. L\'élégance pour vos plus belles occasions.',
    price: 42000,
    category: 'Abaya de cérémonie',
    fabric: 'Soie de Medine',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Noir', hex: '#1A1A1A' },
      { name: 'Bordeaux', hex: '#6B1D3A' },
    ],
    variants: [
      { size: 'S', color: 'Noir', stock: 2, alertThreshold: 2 },
      { size: 'M', color: 'Noir', stock: 4, alertThreshold: 2 },
      { size: 'L', color: 'Noir', stock: 3, alertThreshold: 2 },
      { size: 'XL', color: 'Noir', stock: 1, alertThreshold: 2 },
      { size: 'XXL', color: 'Noir', stock: 2, alertThreshold: 2 },
      { size: 'S', color: 'Bordeaux', stock: 3, alertThreshold: 2 },
      { size: 'M', color: 'Bordeaux', stock: 5, alertThreshold: 2 },
      { size: 'L', color: 'Bordeaux', stock: 2, alertThreshold: 2 },
    ],
    images: ['https://placehold.co/400x500/F5F0E8/3D1A47?text=Aissatou+Royale'],
    isNew: true,
    isActive: true,
    createdAt: weekAgo,
  },
  {
    id: 'p3',
    name: 'Abaya Mariama Sport',
    description: 'Abaya sport en Jersey stretch, idéale pour un look décontracté chic. Confort et modestie au quotidien.',
    price: 15000,
    category: 'Abaya sport',
    fabric: 'Jersey',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Noir', hex: '#1A1A1A' },
      { name: 'Gris anthracite', hex: '#3D3D3D' },
      { name: 'Kaki', hex: '#5C6B4E' },
    ],
    variants: [
      { size: 'XS', color: 'Noir', stock: 3, alertThreshold: 2 },
      { size: 'S', color: 'Noir', stock: 7, alertThreshold: 2 },
      { size: 'M', color: 'Noir', stock: 10, alertThreshold: 2 },
      { size: 'L', color: 'Noir', stock: 6, alertThreshold: 2 },
      { size: 'XL', color: 'Noir', stock: 4, alertThreshold: 2 },
      { size: 'S', color: 'Gris anthracite', stock: 5, alertThreshold: 2 },
      { size: 'M', color: 'Gris anthracite', stock: 8, alertThreshold: 2 },
      { size: 'M', color: 'Kaki', stock: 4, alertThreshold: 2 },
      { size: 'L', color: 'Kaki', stock: 3, alertThreshold: 2 },
    ],
    images: ['https://placehold.co/400x500/F5F0E8/3D1A47?text=Mariama+Sport'],
    isNew: true,
    isActive: true,
    createdAt: weekAgo,
  },
  {
    id: 'p4',
    name: 'Khimar Awa',
    description: 'Khimar en Nida premium, couvrant et fluide. Un essentiel de la garde-robe modeste.',
    price: 12000,
    category: 'Khimar',
    fabric: 'Nida',
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Noir', hex: '#1A1A1A' },
      { name: 'Blanc cassé', hex: '#F0EDE5' },
      { name: 'Taupe', hex: '#8B7D6B' },
    ],
    variants: [
      { size: 'S', color: 'Noir', stock: 12, alertThreshold: 3 },
      { size: 'M', color: 'Noir', stock: 15, alertThreshold: 3 },
      { size: 'L', color: 'Noir', stock: 10, alertThreshold: 3 },
      { size: 'S', color: 'Blanc cassé', stock: 6, alertThreshold: 3 },
      { size: 'M', color: 'Blanc cassé', stock: 8, alertThreshold: 3 },
      { size: 'L', color: 'Blanc cassé', stock: 0, alertThreshold: 3 },
      { size: 'M', color: 'Taupe', stock: 4, alertThreshold: 3 },
    ],
    images: ['https://placehold.co/400x500/F5F0E8/3D1A47?text=Khimar+Awa'],
    isNew: false,
    isActive: true,
    createdAt: monthAgo,
  },
  {
    id: 'p5',
    name: 'Abaya Ndèye Élégance',
    description: 'Abaya de cérémonie en Crepe avec manches papillon et finitions perlées. Pour les femmes qui aiment briller avec sobriété.',
    price: 38000,
    category: 'Abaya de cérémonie',
    fabric: 'Crepe',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Noir', hex: '#1A1A1A' },
      { name: 'Vert émeraude', hex: '#2D6B4E' },
    ],
    variants: [
      { size: 'S', color: 'Noir', stock: 1, alertThreshold: 2 },
      { size: 'M', color: 'Noir', stock: 3, alertThreshold: 2 },
      { size: 'L', color: 'Noir', stock: 2, alertThreshold: 2 },
      { size: 'XL', color: 'Noir', stock: 0, alertThreshold: 2 },
      { size: 'M', color: 'Vert émeraude', stock: 2, alertThreshold: 2 },
      { size: 'L', color: 'Vert émeraude', stock: 3, alertThreshold: 2 },
    ],
    images: ['https://placehold.co/400x500/F5F0E8/3D1A47?text=Ndeye+Elegance'],
    isNew: false,
    isActive: true,
    createdAt: monthAgo,
  },
  {
    id: 'p6',
    name: 'Abaya Coumba Daily',
    description: 'Abaya classique légère en Nida pour tous les jours. Simple, belle, intemporelle.',
    price: 16000,
    category: 'Abaya classique',
    fabric: 'Nida',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Noir', hex: '#1A1A1A' },
      { name: 'Marine', hex: '#1B2A4A' },
      { name: 'Marron', hex: '#5C3A21' },
      { name: 'Gris', hex: '#6B6B6B' },
    ],
    variants: [
      { size: 'XS', color: 'Noir', stock: 4, alertThreshold: 2 },
      { size: 'S', color: 'Noir', stock: 8, alertThreshold: 2 },
      { size: 'M', color: 'Noir', stock: 12, alertThreshold: 2 },
      { size: 'L', color: 'Noir', stock: 9, alertThreshold: 2 },
      { size: 'XL', color: 'Noir', stock: 5, alertThreshold: 2 },
      { size: 'XXL', color: 'Noir', stock: 3, alertThreshold: 2 },
      { size: 'M', color: 'Marine', stock: 6, alertThreshold: 2 },
      { size: 'L', color: 'Marine', stock: 4, alertThreshold: 2 },
      { size: 'M', color: 'Marron', stock: 3, alertThreshold: 2 },
      { size: 'M', color: 'Gris', stock: 5, alertThreshold: 2 },
    ],
    images: ['https://placehold.co/400x500/F5F0E8/3D1A47?text=Coumba+Daily'],
    isNew: false,
    isActive: true,
    createdAt: monthAgo,
  },
  {
    id: 'p7',
    name: 'Abaya Sokhna Prestige',
    description: 'Abaya de cérémonie exclusive en Soie de Médine, avec détails dorés cousus main. Le summum du luxe modeste.',
    price: 45000,
    category: 'Abaya de cérémonie',
    fabric: 'Soie de Medine',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Noir', hex: '#1A1A1A' },
      { name: 'Ivoire', hex: '#F5F0E8' },
    ],
    variants: [
      { size: 'S', color: 'Noir', stock: 2, alertThreshold: 1 },
      { size: 'M', color: 'Noir', stock: 3, alertThreshold: 1 },
      { size: 'L', color: 'Noir', stock: 2, alertThreshold: 1 },
      { size: 'XL', color: 'Noir', stock: 1, alertThreshold: 1 },
      { size: 'S', color: 'Ivoire', stock: 1, alertThreshold: 1 },
      { size: 'M', color: 'Ivoire', stock: 2, alertThreshold: 1 },
      { size: 'L', color: 'Ivoire', stock: 1, alertThreshold: 1 },
    ],
    images: ['https://placehold.co/400x500/F5F0E8/3D1A47?text=Sokhna+Prestige'],
    isNew: true,
    isActive: true,
    createdAt: weekAgo,
  },
  {
    id: 'p8',
    name: 'Abaya Dior Confort',
    description: 'Abaya sport en Jersey premium double épaisseur. Coupe moderne avec poches latérales discrètes.',
    price: 22000,
    category: 'Abaya sport',
    fabric: 'Jersey',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Noir', hex: '#1A1A1A' },
      { name: 'Bleu pétrole', hex: '#1F4E5F' },
    ],
    variants: [
      { size: 'S', color: 'Noir', stock: 6, alertThreshold: 2 },
      { size: 'M', color: 'Noir', stock: 9, alertThreshold: 2 },
      { size: 'L', color: 'Noir', stock: 7, alertThreshold: 2 },
      { size: 'XL', color: 'Noir', stock: 4, alertThreshold: 2 },
      { size: 'S', color: 'Bleu pétrole', stock: 3, alertThreshold: 2 },
      { size: 'M', color: 'Bleu pétrole', stock: 5, alertThreshold: 2 },
      { size: 'L', color: 'Bleu pétrole', stock: 2, alertThreshold: 2 },
    ],
    images: ['https://placehold.co/400x500/F5F0E8/3D1A47?text=Dior+Confort'],
    isNew: false,
    isActive: true,
    createdAt: monthAgo,
  },
];
